[package]
name = "json-pubsub"
version = "0.1.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"

[dependencies]
fxhash = "0.2"
futures = "0.3"
async-std = { version = "1.4", features = ["unstable"] }
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
rmp = "0.8"
rmpv = "0.4"
rmp-serde = "0.14"
rand = "0.7"
lazy_static = "1.4"
bytes = "0.5"
byteorder = "1.3"
failure = "0.1"
pin-utils = "0.1.0-alpha.4"
crossbeam = "0.7"
parking_lot = "0.10"
