[package]
name = "netidx-browser"
version = "0.16.1"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2021"
license = "MIT"
description = "graphical browser for netidx directories"
homepage = "https://netidx.github.io/netidx-book/"
readme = "../README.md"
repository = "https://github.com/estokes/netidx"
documentation = "https://docs.rs/netidx"
keywords = ["networking", "distributed", "kerberos", "tool"]
categories = ["gui"]

[[bin]]
name = "netidx-browser"
path = "src/main.rs"

[features]
default = []
krb5_iov = ["netidx/krb5_iov"]

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "io-util"] }
serde = "1"
chrono = { version = "^0.4.23", features = ["serde"] }
netidx-core = { path = "../netidx-core", version = "^0.16" }
netidx-netproto = { path = "../netidx-netproto", version = "^0.16" }
netidx = { path = "../netidx", version = "^0.16" , default_features = false }
netidx-bscript = { path = "../netidx-bscript", version = "^0.16", default_features = false }
netidx-protocols = { path = "../netidx-protocols", version = "^0.16", default_features = false }
regex = "1"
serde_derive = "1"
serde_json = "1"
bytes = "1"
fxhash = "0.2"
anyhow = "1"
log = "0.4"
env_logger = "0.10"
base64 = "0.21"
parking_lot = "0.12"
indexmap = "1.9"
once_cell = "1"
gdk4 = { version = "0.6", features = ["v4_6"] }
gtk4 = { version = "0.6", features = ["v4_6"] }
pango = "0.17"
gio = "0.17"
glib = "0.17"
gdk-pixbuf = "0.17"
sourceview5 = "0.6"
plotters = { version = "0.3", default_features = false, features = ["datetime", "line_series", "ttf"] }
plotters-backend = "0.3"
lazy_static = "1"
arcstr = { version = "1", features = ["serde"] }
radix_trie = "0.2"
rand = "0.8"
dirs = "4"
